Feature/notification api
BattleQuiche/Backend pull request #2
Opened 2021-06-22 22:48 UTC by MrZyr0

2021-06-22 22:50 UTC, Laroche-Nicolas approved these changes

2021-06-22 23:17 UTC, MaxenceMottard requested changes

2021-06-22 23:17 UTC, MaxenceMottard commented on src/notification/notification.controller.ts
> +@ApiTags('Application Action')
rename this tag

2021-06-22 23:17 UTC, MaxenceMottard commented on src/app.module.ts
> +    ActionModule,
remove this line I've removed it

2021-06-22 23:17 UTC, MaxenceMottard commented on src/main.ts
> +  app.enableCors({
please add condition to enable only if : !process.env.NODE_ENV || process.env.NODE_ENV !== 'production'

2021-06-22 23:17 UTC, MaxenceMottard commented on src/notification/notification.controller.ts
> +@Controller('application')
🤮

2021-06-22 23:17 UTC, MaxenceMottard commented on src/notification/notification.controller.ts
> +  @Post('test-notif')
maybe remove this useless route ?

2021-06-22 23:17 UTC, MaxenceMottard commented on src/notification/notification.service.ts
> +      'mailto:test@test.com',
replace mail with: julien.seixas@ynov.com just for just to piss him off

2021-06-22 23:17 UTC, MaxenceMottard commented on src/notification/notification.service.ts
> +      // const notifications: Promise<SendResult>[] = [];
remove

2021-06-22 23:18 UTC, Laroche-Nicolas commented on src/notification/notification.controller.ts
> +  @Post('test-notif')
No we keep it for a POC

2021-06-23 07:00 UTC, MaxenceMottard approved these changes

2021-06-23 07:01 UTC, merged